FROM ubuntu:18.04

ENV LC_ALL C.UTF-8
ENV LANG en_GB.UTF-8
ENV LANGUAGE en_GB.UTF-8

RUN  apt-get update \
  && apt-get install -y build-essential \
  && apt-get install -y wget \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/*

RUN apt-get -y update
RUN apt-get -y install build-essential tree # General
RUN apt-get -y install python3-dev python3-pip # Python
RUN apt-get -y install libpq-dev # Postgres

COPY . /opt/gr
WORKDIR /opt/gr

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
