# Generated by Django 3.2.7 on 2021-09-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieved_at', models.DateTimeField(auto_now=True)),
                ('red_one_humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('red_one_illumination', models.IntegerField()),
                ('red_one_temperature', models.DecimalField(decimal_places=4, max_digits=5)),
                ('red_two_humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('red_two_illumination', models.IntegerField()),
                ('red_two_temperature', models.DecimalField(decimal_places=4, max_digits=5)),
                ('red_three_humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('red_three_illumination', models.IntegerField()),
                ('red_three_temperature', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieved_at', models.DateTimeField(auto_now=True)),
                ('green_roof_top', models.DecimalField(decimal_places=4, max_digits=5)),
                ('green_roof_bottom', models.DecimalField(decimal_places=4, max_digits=5)),
                ('control_top', models.DecimalField(decimal_places=4, max_digits=5)),
                ('green_roof_middle', models.DecimalField(decimal_places=4, max_digits=5)),
                ('control_bottom', models.DecimalField(decimal_places=4, max_digits=5)),
                ('moist_s0', models.IntegerField()),
                ('moist_s1', models.IntegerField()),
            ],
        ),
    ]
