# Generated by Django 3.2.7 on 2021-09-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roofsensors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambientdata',
            name='recieved_at',
        ),
        migrations.AddField(
            model_name='ambientdata',
            name='recorded_at',
            field=models.DateTimeField(null=True),
        ),
    ]
