# Generated by Django 3.2.7 on 2021-09-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roofsensors', '0003_auto_20210919_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambientdata',
            name='red_one_humidity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ambientdata',
            name='red_one_temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ambientdata',
            name='red_three_humidity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ambientdata',
            name='red_three_temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ambientdata',
            name='red_two_humidity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ambientdata',
            name='red_two_temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='experimentdata',
            name='control_bottom',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='experimentdata',
            name='control_top',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='experimentdata',
            name='green_roof_bottom',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='experimentdata',
            name='green_roof_middle',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='experimentdata',
            name='green_roof_top',
            field=models.FloatField(null=True),
        ),
    ]
