# Generated by Django 3.2.7 on 2021-09-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roofsensors', '0004_auto_20210919_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentdata',
            name='moist_s0',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='experimentdata',
            name='moist_s1',
            field=models.IntegerField(null=True),
        ),
    ]
