# Generated by Django 3.2.7 on 2021-09-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roofsensors', '0006_experimentdata_experiment_difference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentdata',
            old_name='experiment_difference',
            new_name='surface_heat_difference',
        ),
        migrations.AddField(
            model_name='experimentdata',
            name='bottom_difference',
            field=models.FloatField(null=True),
        ),
    ]
